[program:exploreglob-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/exploreglob/artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/exploreglob/storage/logs/worker.log
stopwaitsecs=3600

[program:exploreglob-scheduler]
command=/bin/sh -c 'while true; do php /var/www/exploreglob/artisan schedule:run --no-interaction; sleep 60; done'
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/exploreglob/storage/logs/scheduler.log
