<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\WhatsappAccount;
use App\Models\WhatsappPhoneNumber;
use App\Services\WhatsappCloudApiService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class WhatsappPhoneNumberController extends Controller
{
    public function __construct(private readonly WhatsappCloudApiService $whatsappService)
    {
    }

    /**
     * Show phone numbers page with dynamic data from DB + Meta API sync
     */
    public function index()
    {
        $account = Auth::user()->whatsappAccount;
        $phoneNumber = null;
        $businessProfile = null;
        $hasNumber = false;
        $canRegister = true;

        if ($account) {
            $phoneNumber = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
            
            if ($phoneNumber) {
                $hasNumber = true;
                $canRegister = false;
                
                // Try to sync latest status from Meta API
                try {
                    $details = $this->whatsappService->getPhoneNumberDetails($account, $phoneNumber->phone_number_id);
                    $phoneNumber->update([
                        'quality_rating' => $details['quality_rating'] ?? $phoneNumber->quality_rating,
                        'status' => $details['status'] ?? $phoneNumber->status,
                        'display_name' => $details['verified_name'] ?? $phoneNumber->display_name,
                        'messaging_limit_tier' => $this->extractMessagingTier($details),
                    ]);
                    $phoneNumber = $phoneNumber->fresh();
                    
                    $businessProfile = $this->whatsappService->getBusinessProfile($account, $phoneNumber->phone_number_id);
                } catch (\Throwable $e) {
                    Log::warning('Failed to sync phone number from Meta', ['error' => $e->getMessage()]);
                }
            }
        }

        // Meta Embedded Signup config
        $facebookAppId = config('services.whatsapp.app_id', config('services.facebook.app_id'));
        $whatsappConfigId = config('services.whatsapp.config_id');
        $graphVersion = $account->api_version ?? 'v20.0';

        return view('admin.whatsapp.phone-numbers', compact(
            'account', 'phoneNumber', 'businessProfile', 'hasNumber', 'canRegister',
            'facebookAppId', 'whatsappConfigId', 'graphVersion'
        ));
    }

    /**
     * Handle Meta Embedded Signup callback.
     * 
     * Receives the authorization code + phone_number_id + waba_id from the 
     * Facebook JS SDK embedded signup flow. Exchanges the code for a system user
     * access token, subscribes the app to the WABA, registers the phone number
     * for Cloud API, and stores everything in the database.
     * 
     * This is the Interakt/Wati-style flow where Meta's popup handles everything
     * (business verification, phone number selection, OTP) and we just process the result.
     */
    public function embeddedSignup(Request $request)
    {
        $request->validate([
            'code' => 'required|string',
            'phone_number_id' => 'nullable|string|max:255',
            'waba_id' => 'nullable|string|max:255',
        ]);

        $user = Auth::user();
        $account = $user->whatsappAccount;

        // Enforce 1 number per account
        if ($account) {
            $existing = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
            if ($existing) {
                return response()->json([
                    'success' => false,
                    'message' => 'Your account already has a registered number. Disconnect it first.',
                ], 422);
            }
        }

        // Step 1: Exchange the code for a long-lived access token
        $appId = config('services.whatsapp.app_id', config('services.facebook.app_id'));
        $appSecret = config('services.whatsapp.app_secret', config('services.facebook.app_secret'));
        $redirectUri = config('services.facebook.redirect_uri');

        try {
            $tokenResponse = Http::get('https://graph.facebook.com/v20.0/oauth/access_token', [
                'client_id' => $appId,
                'client_secret' => $appSecret,
                'code' => $request->code,
                'redirect_uri' => '', // Must be empty for codes generated by JS SDK
            ]);

            if ($tokenResponse->failed()) {
                $error = $tokenResponse->json('error.message') ?? 'Token exchange failed';
                Log::error('Meta token exchange failed', ['response' => $tokenResponse->json()]);
                return response()->json(['success' => false, 'message' => $error], 422);
            }

            $accessToken = $tokenResponse->json('access_token');
            if (!$accessToken) {
                return response()->json(['success' => false, 'message' => 'No access token received from Meta.'], 422);
            }

            Log::info('Meta Embedded Signup: token exchange successful');

        } catch (\Throwable $e) {
            Log::error('Meta token exchange exception', ['error' => $e->getMessage()]);
            return response()->json(['success' => false, 'message' => 'Failed to connect with Meta: ' . $e->getMessage()], 500);
        }

        // Step 2: Create or update the WhatsApp account with the new token
        $wabaId = $request->waba_id;
        $phoneNumberId = $request->phone_number_id;

        if (!$account) {
            $account = WhatsappAccount::create([
                'user_id' => $user->id,
                'business_account_id' => $wabaId,
                'phone_number_id' => $phoneNumberId,
                'access_token' => $accessToken,
                'webhook_verify_token' => 'postzy_' . bin2hex(random_bytes(8)),
                'api_version' => 'v20.0',
            ]);
        } else {
            $account->update([
                'access_token' => $accessToken,
                'business_account_id' => $wabaId ?: $account->business_account_id,
                'phone_number_id' => $phoneNumberId ?: $account->phone_number_id,
            ]);
        }

        // Step 3: Subscribe the app to the WABA for webhooks
        if ($wabaId) {
            try {
                $subResponse = Http::withToken($accessToken)->post(
                    "https://graph.facebook.com/v20.0/{$wabaId}/subscribed_apps"
                );
                Log::info('WABA webhook subscription', ['response' => $subResponse->json()]);
            } catch (\Throwable $e) {
                Log::warning('WABA webhook subscription failed', ['error' => $e->getMessage()]);
            }
        }

        // Step 4: If we got phone_number_id from the popup, fetch its details and register it
        if ($phoneNumberId) {
            // Check for duplicate
            $duplicate = WhatsappPhoneNumber::where('phone_number_id', $phoneNumberId)->first();
            if ($duplicate) {
                return response()->json([
                    'success' => false,
                    'message' => 'This phone number is already registered with another account.',
                ], 422);
            }

            // Fetch phone number details from Meta
            $phoneData = [];
            try {
                $phoneData = $this->whatsappService->getPhoneNumberDetails($account, $phoneNumberId);
            } catch (\Throwable $e) {
                Log::warning('Could not fetch phone details from Meta', ['error' => $e->getMessage()]);
            }

            $phoneNumber = WhatsappPhoneNumber::create([
                'whatsapp_account_id' => $account->id,
                'phone_number_id' => $phoneNumberId,
                'phone_number' => $phoneData['display_phone_number'] ?? $phoneNumberId,
                'display_name' => $phoneData['verified_name'] ?? ($phoneData['display_phone_number'] ?? $phoneNumberId),
                'quality_rating' => $phoneData['quality_rating'] ?? 'UNKNOWN',
                'status' => 'CONNECTED',
                'messaging_limit_tier' => $this->extractMessagingTier($phoneData),
                'business_profile_name' => $phoneData['verified_name'] ?? null,
            ]);

            // Register the phone number for Cloud API using a randomly generated 6-digit PIN
            try {
                $pin = sprintf('%06d', random_int(100000, 999999));
                $this->whatsappService->registerPhoneNumber($account, $phoneNumberId, $pin);
                Log::info('Phone number registered for Cloud API', ['phone_number_id' => $phoneNumberId, 'pin' => $pin]);
            } catch (\Throwable $e) {
                Log::warning('Cloud API registration call failed (may already be registered)', ['error' => $e->getMessage()]);
            }

            return response()->json([
                'success' => true,
                'message' => 'WhatsApp number connected successfully via Meta!',
                'phone_number' => $phoneNumber,
            ]);
        }

        // Step 5: If no phone_number_id from popup, try to fetch from WABA
        if ($wabaId) {
            try {
                $numbers = $this->whatsappService->getPhoneNumbers($account);
                $firstNumber = $numbers['data'][0] ?? null;

                if ($firstNumber) {
                    $pid = $firstNumber['id'];
                    $duplicate = WhatsappPhoneNumber::where('phone_number_id', $pid)->first();
                    
                    if (!$duplicate) {
                        $phoneNumber = WhatsappPhoneNumber::create([
                            'whatsapp_account_id' => $account->id,
                            'phone_number_id' => $pid,
                            'phone_number' => $firstNumber['display_phone_number'] ?? $pid,
                            'display_name' => $firstNumber['verified_name'] ?? ($firstNumber['display_phone_number'] ?? $pid),
                            'quality_rating' => $firstNumber['quality_rating'] ?? 'UNKNOWN',
                            'status' => 'CONNECTED',
                            'messaging_limit_tier' => $this->extractMessagingTier($firstNumber),
                            'business_profile_name' => $firstNumber['verified_name'] ?? null,
                        ]);

                        $account->update(['phone_number_id' => $pid]);

                        try {
                            $pin = sprintf('%06d', random_int(100000, 999999));
                            $this->whatsappService->registerPhoneNumber($account, $pid, $pin);
                            Log::info('Phone number registered for Cloud API fallback', ['phone_number_id' => $pid, 'pin' => $pin]);
                        } catch (\Throwable $e) {
                            Log::warning('Cloud API registration call failed', ['error' => $e->getMessage()]);
                        }

                        return response()->json([
                            'success' => true,
                            'message' => 'WhatsApp number connected successfully via Meta!',
                            'phone_number' => $phoneNumber,
                        ]);
                    }
                }
            } catch (\Throwable $e) {
                Log::warning('Could not fetch phone numbers from WABA', ['error' => $e->getMessage()]);
            }
        }

        // Account connected but no phone number was found yet — webhooks will handle it
        return response()->json([
            'success' => true,
            'message' => 'Meta account connected! Your phone number will appear once Meta finishes processing. This may take a few seconds — try refreshing.',
        ]);
    }

    /**
     * Sync phone number status from Meta API
     */
    public function syncStatus(Request $request)
    {
        $account = Auth::user()->whatsappAccount;
        if (!$account) {
            return response()->json(['success' => false, 'message' => 'WhatsApp account not configured.'], 422);
        }

        $phoneNumber = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();

        // If no phone number in DB yet, try to fetch from WABA
        if (!$phoneNumber && $account->business_account_id) {
            try {
                $numbers = $this->whatsappService->getPhoneNumbers($account);
                $firstNumber = $numbers['data'][0] ?? null;

                if ($firstNumber) {
                    $pid = $firstNumber['id'];
                    $phoneNumber = WhatsappPhoneNumber::create([
                        'whatsapp_account_id' => $account->id,
                        'phone_number_id' => $pid,
                        'phone_number' => $firstNumber['display_phone_number'] ?? $pid,
                        'display_name' => $firstNumber['verified_name'] ?? ($firstNumber['display_phone_number'] ?? $pid),
                        'quality_rating' => $firstNumber['quality_rating'] ?? 'UNKNOWN',
                        'status' => 'CONNECTED',
                        'messaging_limit_tier' => $this->extractMessagingTier($firstNumber),
                        'business_profile_name' => $firstNumber['verified_name'] ?? null,
                    ]);
                    $account->update(['phone_number_id' => $pid]);

                    return response()->json([
                        'success' => true,
                        'message' => 'Phone number found and synced from Meta!',
                        'phone_number' => $phoneNumber,
                    ]);
                }
            } catch (\Throwable $e) {
                Log::warning('WABA phone number fetch failed', ['error' => $e->getMessage()]);
            }

            return response()->json(['success' => false, 'message' => 'No phone numbers found on this WABA yet.'], 422);
        }

        if (!$phoneNumber) {
            return response()->json(['success' => false, 'message' => 'No phone number registered.'], 422);
        }

        try {
            $details = $this->whatsappService->getPhoneNumberDetails($account, $phoneNumber->phone_number_id);
            $phoneNumber->update([
                'quality_rating' => $details['quality_rating'] ?? $phoneNumber->quality_rating,
                'status' => $details['status'] ?? $phoneNumber->status,
                'display_name' => $details['verified_name'] ?? $phoneNumber->display_name,
                'messaging_limit_tier' => $this->extractMessagingTier($details),
            ]);

            $businessProfile = $this->whatsappService->getBusinessProfile($account, $phoneNumber->phone_number_id);
            if (!empty($businessProfile['data'][0])) {
                $profile = $businessProfile['data'][0];
                $phoneNumber->update([
                    'business_profile_name' => $profile['vertical'] ?? $phoneNumber->business_profile_name,
                    'business_profile_category' => $profile['vertical'] ?? $phoneNumber->business_profile_category,
                    'business_profile_description' => $profile['description'] ?? $phoneNumber->business_profile_description,
                ]);
            }

            return response()->json([
                'success' => true, 
                'message' => 'Phone number synced with Meta.',
                'phone_number' => $phoneNumber->fresh(),
            ]);
        } catch (\Throwable $e) {
            return response()->json(['success' => false, 'message' => 'Sync failed: ' . $e->getMessage()], 422);
        }
    }

    /**
     * Update business profile
     */
    public function updateProfile(Request $request)
    {
        $request->validate([
            'about' => 'nullable|string|max:139',
            'description' => 'nullable|string|max:512',
            'email' => 'nullable|email|max:128',
            'vertical' => 'nullable|string|max:255',
            'websites' => 'nullable|array|max:2',
            'websites.*' => 'url|max:256',
            'profile_picture' => 'nullable|image|mimes:jpeg,png,jpg|max:5120', // max 5MB
        ]);

        $account = Auth::user()->whatsappAccount;
        if (!$account) {
            return back()->with('error', 'WhatsApp account not configured.');
        }

        $phoneNumber = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
        if (!$phoneNumber) {
            return back()->with('error', 'No phone number registered.');
        }

        try {
            $profileData = array_filter([
                'messaging_product' => 'whatsapp',
                'about' => $request->about,
                'description' => $request->description,
                'email' => $request->email,
                'vertical' => $request->vertical,
                'websites' => $request->websites,
            ], fn($v) => $v !== null);

            // Handle Profile Picture
            if ($request->hasFile('profile_picture')) {
                $file = $request->file('profile_picture');
                $handle = $this->whatsappService->uploadProfilePicture($account, $file->getPathname(), $file->getMimeType());
                $profileData['profile_picture_handle'] = $handle;
            }

            $this->whatsappService->updateBusinessProfile($account, $phoneNumber->phone_number_id, $profileData);

            $phoneNumber->update([
                'business_profile_category' => $request->vertical ?? $phoneNumber->business_profile_category,
                'business_profile_description' => $request->description ?? $phoneNumber->business_profile_description,
            ]);

            return back()->with('success', 'Business profile updated successfully.');
        } catch (\Throwable $e) {
            return back()->with('error', 'Failed to update profile: ' . $e->getMessage());
        }
    }

    /**
     * Disconnect/deregister the phone number
     */
    public function disconnect(Request $request)
    {
        $account = Auth::user()->whatsappAccount;
        if (!$account) {
            return response()->json(['success' => false, 'message' => 'WhatsApp account not configured.'], 422);
        }

        $phoneNumber = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
        if (!$phoneNumber) {
            return response()->json(['success' => false, 'message' => 'No phone number to disconnect.'], 422);
        }

        try {
            $this->whatsappService->deregisterPhoneNumber($account, $phoneNumber->phone_number_id);
        } catch (\Throwable $e) {
            Log::warning('Meta deregistration failed (proceeding with local removal)', ['error' => $e->getMessage()]);
        }

        $phoneNumber->delete();
        $account->update(['phone_number_id' => null]);

        return response()->json(['success' => true, 'message' => 'Phone number disconnected successfully.']);
    }

    /**
     * Manual Registration (Step 1): Add phone number ID
     */
    public function register(Request $request)
    {
        $request->validate([
            'phone_number_id' => 'required|string|max:255',
        ]);

        $account = Auth::user()->whatsappAccount;
        if (!$account) {
            return response()->json(['success' => false, 'message' => 'WhatsApp account not configured.'], 422);
        }

        $existing = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
        if ($existing) {
            return response()->json(['success' => false, 'message' => 'Your account already has a registered number.'], 422);
        }

        $phoneNumberId = $request->phone_number_id;

        try {
            $phoneData = $this->whatsappService->getPhoneNumberDetails($account, $phoneNumberId);
            
            $phoneNumber = WhatsappPhoneNumber::create([
                'whatsapp_account_id' => $account->id,
                'phone_number_id' => $phoneNumberId,
                'phone_number' => $phoneData['display_phone_number'] ?? $phoneNumberId,
                'display_name' => $phoneData['verified_name'] ?? ($phoneData['display_phone_number'] ?? $phoneNumberId),
                'quality_rating' => $phoneData['quality_rating'] ?? 'UNKNOWN',
                'status' => 'PENDING',
                'messaging_limit_tier' => $this->extractMessagingTier($phoneData),
            ]);

            $account->update(['phone_number_id' => $phoneNumberId]);

            return response()->json([
                'success' => true,
                'message' => 'Phone number added successfully. Please verify it.',
                'phone_number' => $phoneNumber,
            ]);
        } catch (\Throwable $e) {
            return response()->json(['success' => false, 'message' => 'Failed to add phone number: ' . $e->getMessage()], 422);
        }
    }

    /**
     * Manual Registration (Step 2): Request verification code
     */
    public function requestCode(Request $request)
    {
        $request->validate([
            'code_method' => 'required|in:SMS,VOICE',
        ]);

        $account = Auth::user()->whatsappAccount;
        if (!$account) {
            return response()->json(['success' => false, 'message' => 'WhatsApp account not configured.'], 422);
        }

        $phoneNumber = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
        if (!$phoneNumber) {
            return response()->json(['success' => false, 'message' => 'No phone number registered.'], 422);
        }

        try {
            $this->whatsappService->requestVerificationCode($account, $phoneNumber->phone_number_id, $request->code_method);
            return response()->json([
                'success' => true,
                'message' => 'Verification code requested via ' . $request->code_method,
            ]);
        } catch (\Throwable $e) {
            return response()->json(['success' => false, 'message' => 'Failed to request code: ' . $e->getMessage()], 422);
        }
    }

    /**
     * Manual Registration (Step 3): Verify code
     */
    public function verifyCode(Request $request)
    {
        $request->validate([
            'code' => 'required|string|max:10',
        ]);

        $account = Auth::user()->whatsappAccount;
        if (!$account) {
            return response()->json(['success' => false, 'message' => 'WhatsApp account not configured.'], 422);
        }

        $phoneNumber = WhatsappPhoneNumber::where('whatsapp_account_id', $account->id)->first();
        if (!$phoneNumber) {
            return response()->json(['success' => false, 'message' => 'No phone number registered.'], 422);
        }

        try {
            $this->whatsappService->verifyCode($account, $phoneNumber->phone_number_id, $request->code);
            
            // Register for Cloud API
            $this->whatsappService->registerPhoneNumber($account, $phoneNumber->phone_number_id);

            $phoneNumber->update(['status' => 'CONNECTED']);

            return response()->json([
                'success' => true,
                'message' => 'Phone number verified and connected successfully!',
            ]);
        } catch (\Throwable $e) {
            return response()->json(['success' => false, 'message' => 'Verification failed: ' . $e->getMessage()], 422);
        }
    }

    /**
     * Extract messaging tier from Meta API response
     */
    private function extractMessagingTier(array $details): string
    {
        if (isset($details['messaging_limit_tier'])) {
            return match($details['messaging_limit_tier']) {
                'TIER_50' => '50',
                'TIER_250' => '250',
                'TIER_1K' => '1K',
                'TIER_10K' => '10K',
                'TIER_100K' => '100K',
                'TIER_UNLIMITED' => 'UNLIMITED',
                default => $details['messaging_limit_tier'],
            };
        }
        return '1K';
    }
}
